### ISSUE TITLE
Sales Analysis of Super Market

### ISSUE THREAD

**Issue by VikashPR** [StoryTelling-UsingData/18CSE301J-Projects#281]
Sales Analysis of Super Market

@Sainath3679 @gh9049 @PRABHAV-RA2011003011010 @pm0205 @sesha-vineeth-1 @siddhardha123 

Guys please mention your team mates id here, if missed out

_Originally posted by @VikashPR in https://github.com/VikashPR/18CSE301J-Projects/issues/266#issuecomment-1490547536_

**Comment by gh9049** [comment]
what id's bro

**Comment by VikashPR** [comment]
> what id's bro
> like what's the purpose

bro we need your team members GitHub ID to add them as contributors in the home page

**Comment by VikashPR** [comment]
@all-contributors please add @Sainath3679 for content, example.

**Comment by VikashPR** [comment]
@all-contributors please add @gh9049 for content, example.

**Comment by VikashPR** [comment]
@all-contributors please add @PRABHAV-RA2011003011010 for content, example.

**Comment by VikashPR** [comment]
@all-contributors please add @pm0205 for content, example.

**Comment by VikashPR** [comment]
@all-contributors please add @sesha-vineeth-1 for content, example.

**Comment by VikashPR** [comment]
@all-contributors please add @siddhardha123 for content, example.
