### ISSUE TITLE
Layoffs

### ISSUE THREAD

**Issue by kishorekhan2003** [StoryTelling-UsingData/18CSE301J-Projects#500]
Add to contributors @kishorekhan2003 @sudhersankv @harikesh11 @allenben18

**Comment by VikashPR** [comment]
@all-contributors please add  @kishorekhan2003 for content, example.

**Comment by VikashPR** [comment]
@all-contributors please add @harikesh11 for example, content.

**Comment by VikashPR** [comment]
@all-contributors please add @allenben18 for content, example.
